//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rbnDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audience
    {
        public Audience()
        {
            this.Books = new HashSet<Book>();
            this.ReaderNotes = new HashSet<ReaderNotes>();
            this.Ratings = new HashSet<Ratings>();
        }
    
        public int AudienceId { get; set; }
        public string Name { get; set; }
        public bool Enabled { get; set; }
    
        public virtual ICollection<Book> Books { get; set; }
        public virtual ICollection<ReaderNotes> ReaderNotes { get; set; }
        public virtual ICollection<Ratings> Ratings { get; set; }
    }
}
