//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rbnDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ratings
    {
        public int RatingId { get; set; }
        public int UserId { get; set; }
        public int ReaderNoteId { get; set; }
        public int Rating1 { get; set; }
        public Nullable<int> AudienceId { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Audience Audience { get; set; }
        public virtual ReaderNotes ReaderNote { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
