//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rbnDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReaderNote
    {
        public ReaderNote()
        {
            this.Ratings = new HashSet<Rating>();
        }
    
        public int ReaderNoteId { get; set; }
        public int BookId { get; set; }
        public int ReaderId { get; set; }
        public int Rating { get; set; }
        public int AudienceId { get; set; }
        public string Note { get; set; }
        public bool Notify { get; set; }
        public Nullable<System.DateTime> DateNotified { get; set; }
        public string EmailAddress { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
    
        public virtual Audience Audience { get; set; }
        public virtual Book Book { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
    }
}
