//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rbnDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<bool> NeedsApproval { get; set; }
        public Nullable<bool> AccountLocked { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
