//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rbnDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.webpages_Roles = new HashSet<webpages_Roles>();
            this.ReaderNotes = new HashSet<ReaderNotes>();
            this.Ratings = new HashSet<Ratings>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
        public virtual ICollection<ReaderNotes> ReaderNotes { get; set; }
        public virtual ICollection<Ratings> Ratings { get; set; }
    }
}
